// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry");
var State = require("./state");

var state_003 = /* userId : Some */[1];

var state_004 = /* users : :: */[
  /* record */[
    /* id */1,
    /* email */"sean@bushi.do",
    /* name : Some */["Sean Grove"],
    /* status : Online */1,
    /* username */"sgrove"
  ],
  /* :: */[
    /* record */[
      /* id */4,
      /* email */"dwwoelfel@gmail.com",
      /* name : Some */["Daniel Woelfel"],
      /* status : Online */1,
      /* username */"dww"
    ],
    /* :: */[
      /* record */[
        /* id */2,
        /* email */"info@sachagreif.com",
        /* name : Some */["Sacha Greif"],
        /* status : Away */2,
        /* username */"sg"
      ],
      /* :: */[
        /* record */[
          /* id */3,
          /* email */"sbensu@gmail.com",
          /* name : None */0,
          /* status : Offline */0,
          /* username */"sbensu"
        ],
        /* [] */0
      ]
    ]
  ]
];

var state_005 = /* channels : :: */[
  /* record */[
    /* id */0,
    /* title */"Classical",
    /* loading : false */0,
    /* activities : :: */[
      /* record */[
        /* content */"Move along",
        /* userId */3,
        /* createdAt */0
      ],
      /* :: */[
        /* record */[
          /* content */"Nothing to see here, eh?",
          /* userId */1,
          /* createdAt */1
        ],
        /* :: */[
          /* record */[
            /* content */"When are we going to get a more interesting lobby?",
            /* userId */1,
            /* createdAt */2
          ],
          /* :: */[
            /* record */[
              /* content */"Sir, move along",
              /* userId */3,
              /* createdAt */3
            ],
            /* :: */[
              /* record */[
                /* content */'This message contains the phrase "search" as the seventh to last word.',
                /* userId */3,
                /* createdAt */3
              ],
              /* :: */[
                /* record */[
                  /* content */"Sir, move along",
                  /* userId */3,
                  /* createdAt */3
                ],
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ],
    /* userIds */Curry._2(State.UserIdSet[/* add */3], 2, Curry._2(State.UserIdSet[/* add */3], 1, State.UserIdSet[/* empty */0])),
    /* media : record */[
      /* order */0,
      /* src : None */0
    ],
    /* mediaState : Paused */1,
    /* playlist : :: */[
      /* record */[
        /* order */0,
        /* src : Some */["http://www.mfiles.co.uk/mp3-downloads/frederic-chopin-piano-sonata-2-op35-3-funeral-march.mp3"]
      ],
      /* :: */[
        /* record */[
          /* order */1,
          /* src : Some */["http://www.mfiles.co.uk/mp3-downloads/Dvorak-Symphony9-2-from-the-New-World.mp3"]
        ],
        /* :: */[
          /* record */[
            /* order */2,
            /* src : Some */["http://www.mfiles.co.uk/mp3-downloads/moonlight-movement1.mp3"]
          ],
          /* :: */[
            /* record */[
              /* order */3,
              /* src : Some */["http://www.mfiles.co.uk/mp3-downloads/beethoven-piano-sonata-pathetique-2.mp3"]
            ],
            /* [] */0
          ]
        ]
      ]
    ]
  ],
  /* :: */[
    /* record */[
      /* id */1,
      /* title */"Trance",
      /* loading : false */0,
      /* activities : :: */[
        /* record */[
          /* content */"Not enough progressive trance in here, really...",
          /* userId */2,
          /* createdAt */0
        ],
        /* [] */0
      ],
      /* userIds */Curry._2(State.UserIdSet[/* add */3], 2, Curry._2(State.UserIdSet[/* add */3], 1, State.UserIdSet[/* empty */0])),
      /* media : record */[
        /* order */0,
        /* src : None */0
      ],
      /* mediaState : Paused */1,
      /* playlist : :: */[
        /* record */[
          /* order */0,
          /* src : Some */["https://dl.dropboxusercontent.com/u/412963/music/Gareth%20Emery%20feat.%20Christina%20Novelli%20-%20Concrete%20Angel.mp3"]
        ],
        /* [] */0
      ]
    ],
    /* :: */[
      /* record */[
        /* id */2,
        /* title */"Lobby?",
        /* loading : false */0,
        /* activities : :: */[
          /* record */[
            /* content */"> The ReasonCup logo http://reasoncup.com/resources/public/img/ReasonCup2016.png",
            /* userId */2,
            /* createdAt */1
          ],
          /* :: */[
            /* record */[
              /* content */"this is the last",
              /* userId */1,
              /* createdAt */99
            ],
            /* :: */[
              /* record */[
                /* content */"/me agrees with the previous message :+1: rgb(150,0,0) #000 #ff00ff",
                /* userId */1,
                /* createdAt */5
              ],
              /* :: */[
                /* record */[
                  /* content */"Paaassstttiiieee!!!\n\n          Nice!\n          ...right? ",
                  /* userId */1,
                  /* createdAt */4
                ],
                /* :: */[
                  /* record */[
                    /* content */"this is https://pbs.twimg.com/profile_images/766692876105289729/NZ16ZsLq_normal.jpg third",
                    /* userId */1,
                    /* createdAt */2
                  ],
                  /* :: */[
                    /* record */[
                      /* content */"this is second to last rgb(111,222,000)",
                      /* userId */4,
                      /* createdAt */3
                    ],
                    /* :: */[
                      /* record */[
                        /* content */"Reason will prevail!",
                        /* userId */4,
                        /* createdAt */9
                      ],
                      /* :: */[
                        /* record */[
                          /* content */"If you can see this, SEARCH WORKS~~~!",
                          /* userId */3,
                          /* createdAt */100
                        ],
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ],
        /* userIds */Curry._2(State.UserIdSet[/* add */3], 4, Curry._2(State.UserIdSet[/* add */3], 3, Curry._2(State.UserIdSet[/* add */3], 2, Curry._2(State.UserIdSet[/* add */3], 1, State.UserIdSet[/* empty */0])))),
        /* media : record */[
          /* order */0,
          /* src : None */0
        ],
        /* mediaState : Paused */1,
        /* playlist : :: */[
          /* record */[
            /* order */0,
            /* src : Some */["https://dl.dropboxusercontent.com/u/412963/music/%E4%BA%B2%E7%88%B1%E7%9A%84%E4%BD%A0%E6%80%8E%E4%B9%88%E4%B8%8D%E5%9C%A8%E6%88%91%E8%BA%AB%E8%BE%B9.m4a"]
          ],
          /* :: */[
            /* record */[
              /* order */1,
              /* src : Some */["https://dl.dropboxusercontent.com/u/412963/music/%E5%A5%BD%E5%BF%83%E5%88%86%E6%89%8B%20Candy%20Lo%20feat.%20%E7%8E%8B%E5%8A%9B%E5%AE%8F.mp3"]
            ],
            /* :: */[
              /* record */[
                /* order */2,
                /* src : Some */["https://dl.dropboxusercontent.com/u/412963/Why%20This%20Kolaveri%20Di%20Full%20Song%20Promo%20Video%20in%20HD%20-%20.mp3"]
              ],
              /* :: */[
                /* record */[
                  /* order */3,
                  /* src : Some */["https://dl.dropboxusercontent.com/u/412963/music/%E4%BA%B2%E7%88%B1%E7%9A%84%20%EF%BC%8D%20%E5%BE%90%E8%8B%A5%E7%91%84.mp3"]
                ],
                /* :: */[
                  /* record */[
                    /* order */4,
                    /* src : Some */["https://dl.dropboxusercontent.com/u/412963/music/Money%20Trees%20-%20Kendrick%20Lamar.mp3"]
                  ],
                  /* :: */[
                    /* record */[
                      /* order */5,
                      /* src : Some */["https://dl.dropboxusercontent.com/u/412963/music/Armin%20van%20Buuren%20feat.%20Trevor%20Guthrie%20-%20This%20Is%20What%20It%20Feels%20Like.mp3"]
                    ],
                    /* :: */[
                      /* record */[
                        /* order */6,
                        /* src : Some */["https://gp1.wpc.edgecastcdn.net/802892/http_private_production_west/songs/mp3_files/1499565/original/05_Last_Train_To_New_Jersey.mp3?e8817609673e6ceae29a01aebbc7efb2d22071b611f2c5d20b95874752890b0c4edd662116821b9083ff0faeaa15f2fd4e18d85478e697b4e0f50fc5404f165440cbf4d8a9da9a5843afbac36da6bc407e62d68502dff3e1510b7c2863ddb46a072c70740ad2d2cda77f3ce85e75b6dc01517324d33481daa7169fbf58b16d7108d36ad57945d3f0352d86322cc3fb302862b16711"]
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ],
      /* [] */0
    ]
  ]
];

var state = /* record */[
  /* rightSidebarOpen : false */0,
  /* leftSidebarOpen : false */0,
  /* selectedChannelId */2,
  state_003,
  state_004,
  state_005,
  /* userMessageFocused : false */0,
  /* searchFormFocused : false */0,
  /* userMenuOpen : false */0,
  /* search : None */0,
  /* title */"Kandan",
  /* volume */0.75,
  /* lastVolume */0.75
];

exports.state = state;
/* state Not a pure module */
