// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive");

function matchRegex(string, regex) {
  return Js_primitive.null_to_opt(string.match(regex));
}

function matchString(s1, s2) {
  return Js_primitive.null_to_opt(s1.match(s2));
}

exports.matchRegex  = matchRegex;
exports.matchString = matchString;
/* No side effect */
