// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';


var Uint16Array = /* module */[];

var Crypto = /* module */[];

function now_ts() {
  return new window.Date().getTime();
}

var $$Date = /* module */[/* now_ts */now_ts];

exports.Uint16Array = Uint16Array;
exports.Crypto      = Crypto;
exports.$$Date      = $$Date;
/* No side effect */
