// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';

var $$Map    = require("bs-platform/lib/js/map");
var $$Set    = require("bs-platform/lib/js/set");
var $$String = require("bs-platform/lib/js/string");
var Caml_obj = require("bs-platform/lib/js/caml_obj");

var compare = Caml_obj.caml_compare;

var UserIdType = /* module */[/* compare */compare];

var UserIdSet = $$Set.Make(UserIdType);

var EmojiPairs = $$Map.Make([$$String.compare]);

function stringOfAction(action) {
  if (typeof action === "number") {
    return "VolumeMuteToggled";
  }
  else {
    switch (action.tag | 0) {
      case 0 : 
          return "SearchFormFocused";
      case 1 : 
          return "SidebarToggled";
      case 2 : 
          return "SearchUpdated";
      case 3 : 
          return "ChannelSelected";
      case 4 : 
          return "ChannelSelectedByIndex";
      case 5 : 
          return "SongSelected";
      case 6 : 
          return "MediaStateUpdated";
      case 7 : 
          return "ChatBoxFocused";
      case 8 : 
          return "UserMenuToggled";
      case 9 : 
          return "MsgSubmitted";
      case 10 : 
          return "AppTitleUpdated";
      case 11 : 
          return "VolumeSet";
      case 12 : 
          return "VolumentIncremented";
      case 13 : 
          return "VolumentDecremented";
      case 14 : 
          return "Log";
      case 15 : 
          return "Alert";
      
    }
  }
}

exports.UserIdType     = UserIdType;
exports.UserIdSet      = UserIdSet;
exports.EmojiPairs     = EmojiPairs;
exports.stringOfAction = stringOfAction;
/* UserIdSet Not a pure module */
