// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';


function repeat_string(str, count) {
  if (count !== 0) {
    var half = count / 2 | 0;
    var result = str;
    while(result.length <= half) {
      result = result + result;
    };
    return result + result.substring(0, count - result.length | 0);
  }
  else {
    return "";
  }
}

function to_hex_string(n, l) {
  var s = n.toString(16);
  var c = s.length;
  if (c > l) {
    return s.substring(0, l);
  }
  else if (c < l) {
    return repeat_string("0", l - c | 0) + s;
  }
  else {
    return s;
  }
}

var Crypto = /* module */[];

function squuid() {
  var a = window.crypto.getRandomValues(new Uint16Array(/* int array */[6]));
  var b1 = a[0];
  var b2 = a[1];
  var b3 = a[2];
  var b4 = a[3];
  var b5 = a[4];
  var b6 = a[5];
  var _base = Date.now();
  var base = to_hex_string(Math.round(_base / 1000.0), 8);
  return base + ("-" + (to_hex_string(b1, 4) + ("-" + (to_hex_string(b2 & 4095 | 16384, 4) + ("-" + (to_hex_string(b3 & 16383 | 32768, 4) + ("-" + (to_hex_string(b4, 4) + (to_hex_string(b5, 4) + to_hex_string(b6, 4))))))))));
}

exports.repeat_string = repeat_string;
exports.to_hex_string = to_hex_string;
exports.Crypto        = Crypto;
exports.squuid        = squuid;
/* No side effect */
